### ISSUE TITLE
"TypeError: must be str, not bytes"

### ISSUE THREAD

**Issue by goatlikeKarthos** [SignalMedia/Signal-1M-Tools#7]
When I enter this command in cmd:

` python convert-to-trec.py -i C:\Users\User\Desktop\signaldata\sample-1M.jsonl -o C:\Users\User\Desktop\signaldata\trec.jsonl`

I get the following Error Message: 

file "convert-to-trec.py", line 47, in main
  fout.write(tecdoc.encode('utf-8'))
TypeError: must be str,  not bytes

What causes this? Im also not sure if the file im writing into should already exist, in my case it doesnt

Also, another Error that appeared when trying to index the Data into Elasticsearch: At some random Number (E.g. 15000, 21000) the Indexing Script encounters an Error and Stops. 

____________________________________________CMD LOG OF INDEXING ERROR_________________________________________

Added document: 21567
Added document: 21568
Added document: 21569
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python34\Lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\Lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\Lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\Lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\Lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x030F96D0>: Failed to establish a new connection: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden

**Comment by goatlikeKarthos** [comment]
The fix seems to be to change the file like this:

            trecdoc += u"</DOC>\n"
            fout.buffer.write(trecdoc.encode('utf-8'))
           # try: # py27
           #     fout.buffer.write(trecdoc.encode('utf-8'))
           # except TypeError: # py34
            #    fout.write(trecdoc)

**Comment by dyaaalbakour** [comment]
thanks for your comments @goatlikeKarthos! 
With regards to your first comment, you need to pass one the uncompressed file (i.e. in jsonl format) to be able to run the script and it should work fine. you don't need to create the file. Also it seems you have a typo in that error message 'tecdoc' not 'trecdoc'. It might be worth recloning the repo and trying again.
With regards to the second, I could not replicate the error. If you still have the problem, please open a new issue, and detail the version of ES you are using.  
Best wishes
Dyaa
