### ISSUE TITLE
Indexing stops at 19170

### ISSUE THREAD

**Issue by FelixHornberger** [SignalMedia/Signal-1M-Tools#8]
Traceback (most recent call last):
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\knott\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\knott\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\knott\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\knott\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "C:\Users\knott\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 948, in send
    self.connect()
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002614F64BD90>: Failed to establish a new connection: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerk
adresse oder Anschluss) nur jeweils einmal verwendet werden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /articles/article (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000261
4F64BD90>: Failed to establish a new connection: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\knott\Documents\stuff\Signal-1M-Tools-master\index_articles.py", line 10, in <module>
    requests.post(url=es_url + '/articles/article', data=line)
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\knott\Documents\PythonKurs\uebung2\venv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /articles/article (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000
2614F64BD90>: Failed to establish a new connection: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden'))
PS C:\Users\knott\Documents\stuff\Signal-1M-Tools-master>

**Comment by FelixHornberger** [comment]
A fix for this would be adding a try except phrase:
import sys
import requests

es_url = sys.argv[1]
filename = sys.argv[2]

doc_num_successful = 0
doc_num_failed = 0

with open(filename) as f:
    for line in f:
        try:
            requests.post(url=es_url + '/articles/article', data=line)
            print('Added document:\t' + str(doc_num_successful+1))
            doc_num_successful += 1
        except:
            doc_num_failed += 1
